#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillageMVCWebApplication.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eldersDB")]
	public partial class EldersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSenior(Senior instance);
    partial void UpdateSenior(Senior instance);
    partial void DeleteSenior(Senior instance);
    #endregion
		
		public EldersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["eldersDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EldersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EldersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EldersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EldersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Senior> Seniors
		{
			get
			{
				return this.GetTable<Senior>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seniors")]
	public partial class Senior : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SeniorId;
		
		private string _nameOfSenior;
		
		private System.Nullable<System.DateTime> _birthdate;
		
		private System.Nullable<int> _seniorityLevel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSeniorIdChanging(int value);
    partial void OnSeniorIdChanged();
    partial void OnnameOfSeniorChanging(string value);
    partial void OnnameOfSeniorChanged();
    partial void OnbirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdateChanged();
    partial void OnseniorityLevelChanging(System.Nullable<int> value);
    partial void OnseniorityLevelChanged();
    #endregion
		
		public Senior()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeniorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SeniorId
		{
			get
			{
				return this._SeniorId;
			}
			set
			{
				if ((this._SeniorId != value))
				{
					this.OnSeniorIdChanging(value);
					this.SendPropertyChanging();
					this._SeniorId = value;
					this.SendPropertyChanged("SeniorId");
					this.OnSeniorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameOfSenior", DbType="NVarChar(50)")]
		public string nameOfSenior
		{
			get
			{
				return this._nameOfSenior;
			}
			set
			{
				if ((this._nameOfSenior != value))
				{
					this.OnnameOfSeniorChanging(value);
					this.SendPropertyChanging();
					this._nameOfSenior = value;
					this.SendPropertyChanged("nameOfSenior");
					this.OnnameOfSeniorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="Date")]
		public System.Nullable<System.DateTime> birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this.OnbirthdateChanging(value);
					this.SendPropertyChanging();
					this._birthdate = value;
					this.SendPropertyChanged("birthdate");
					this.OnbirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seniorityLevel", DbType="Int")]
		public System.Nullable<int> seniorityLevel
		{
			get
			{
				return this._seniorityLevel;
			}
			set
			{
				if ((this._seniorityLevel != value))
				{
					this.OnseniorityLevelChanging(value);
					this.SendPropertyChanging();
					this._seniorityLevel = value;
					this.SendPropertyChanged("seniorityLevel");
					this.OnseniorityLevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
