<?xml version="1.0" encoding="utf-8"?><Database Name="eldersDB" Class="EldersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=eldersDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="eldersDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Seniors" Member="Seniors">
    <Type Name="Senior">
      <Column Name="SeniorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nameOfSenior" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="seniorityLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>